import { StyleSheet, Dimensions } from 'react-native';
import { colors, fonts } from '../styles/theme';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  header: { 
    padding: 20, 
    borderBottomWidth: 1, 
    borderBottomColor: colors.border, 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center' 
  },
  headerText: { fontSize: 20, fontWeight: 'bold', color: colors.textPrimary },
  loading: { fontSize: 18, color: colors.textSecondary, fontFamily: fonts.body, marginTop: 40, textAlign: 'center' },
  profileHeader: { flexDirection: 'row', alignItems: 'center', padding: 20 },
  avatar: { width: 90, height: 90, borderRadius: 45, marginRight: 18 },
  statsContainer: { flexDirection: 'row', justifyContent: 'space-around', flex: 1 },
  stat: { alignItems: 'center' },
  statNumber: { fontSize: 18, fontWeight: 'bold', color: colors.textPrimary },
  statNumberHighlight: { color: colors.accent },
  statLabel: { fontSize: 14, color: colors.textSecondary },
  bioContainer: { paddingHorizontal: 20, marginBottom: 20 },
  name: { fontSize: 16, fontWeight: 'bold', color: colors.textPrimary, fontFamily: fonts.heading },
  bio: { fontSize: 14, color: colors.textPrimary, fontFamily: fonts.body, marginTop: 5 },
  actionsContainer: { flexDirection: 'row', justifyContent: 'space-around', paddingHorizontal: 20, marginBottom: 20 },
  button: { backgroundColor: colors.card, paddingVertical: 10, paddingHorizontal: 20, borderRadius: 5, alignItems: 'center', flex: 1, marginHorizontal: 5, borderWidth: 1, borderColor: colors.border },
  buttonText: { color: colors.textPrimary, fontWeight: 'bold', fontSize: 14 },
  sectionTitle: { fontSize: 22, fontWeight: 'bold', color: colors.accent, fontFamily: fonts.heading, marginBottom: 12, paddingHorizontal: 20 },
  postCard: { backgroundColor: colors.card, borderRadius: 0, marginBottom: 14, shadowColor: colors.border, shadowOpacity: 0.12, shadowRadius: 8, elevation: 2, borderWidth: 1, borderColor: colors.border },
  postHeader: { flexDirection: 'row', alignItems: 'center', padding: 10 },
  authorName: { color: colors.textPrimary, fontWeight: 'bold', fontFamily: fonts.heading, fontSize: 16 },
  postImage: { width: '100%', height: 300 },
  placeholderImage: { width: '100%', height: 300, backgroundColor: '#e0e0e0' },
  postActions: { flexDirection: 'row', padding: 10 },
  actionButton: { marginRight: 15, flexDirection: 'column', alignItems: 'center' },
  likeButtonContent: { flexDirection: 'column', alignItems: 'center' },
  likeCount: { color: colors.textPrimary, fontSize: 12, marginTop: 2 },
  captionContainer: { paddingHorizontal: 10, paddingBottom: 10 },
  caption: { color: colors.textPrimary, fontFamily: fonts.body, fontSize: 14 },
  postTimestamp: { color: colors.textSecondary, fontSize: 12, marginTop: 4, fontFamily: fonts.body },
  postAvatar: { width: 40, height: 40, borderRadius: 20, marginRight: 10 },
  postGrid: { flex: 1 },
  postItem: { width: (width / 3) - 2, height: (width / 3) - 2, margin: 1 },
  postImage: { width: '100%', height: '100%' },
  logoutButton: {
    backgroundColor: colors.accent,
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 8,
    alignItems: 'center',
  },
  logoutButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
  },
});