import { StyleSheet } from 'react-native';
import { colors, fonts } from '../styles/theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 0,
    paddingBottom: 0,
  },
  vitaText: {
    fontSize: 48,
    fontFamily: fonts.heading,
    color: colors.logoOrange,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
    marginTop: -120,
    marginBottom: 36,
  },
  title: {
    fontSize: 38,
    fontFamily: fonts.heading,
    color: colors.titles,
    marginTop: 24,
    marginBottom: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 20,
    color: colors.textPrimary,
    fontFamily: fonts.body,
    marginBottom: 44,
    textAlign: 'center',
    paddingHorizontal: 10,
    lineHeight: 30,
    letterSpacing: 0.5,
  },
  button: {
    backgroundColor: colors.accent,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 40,
    marginBottom: 16,
  },
  buttonText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontFamily: fonts.heading,
    fontWeight: 'bold',
  },
  secondaryButton: {
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 48,
    marginBottom: 0,
    alignItems: 'center',
    width: '100%',
    shadowColor: colors.accent,
    shadowOpacity: 0.13,
    shadowRadius: 6,
    elevation: 2,
  },
  secondaryButtonText: {
    color: colors.buttonText,
    fontSize: 20,
    fontFamily: fonts.heading,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  linkButton: {
    marginTop: 18,
    alignSelf: 'center',
  },
  linkButtonText: {
    color: colors.link,
    fontSize: 15,
    textAlign: 'center',
    fontFamily: fonts.body,
  },
  signupBox: {
    backgroundColor: colors.card,
    borderRadius: 18,
    padding: 24,
    marginBottom: 28,
    alignItems: 'center',
    width: '100%',
    shadowColor: colors.border,
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 3,
  },
  brownLinkText: {
    color: colors.titles,
    fontSize: 16,
    textAlign: 'center',
    fontFamily: fonts.body,
    textDecorationLine: 'underline',
    letterSpacing: 0.2,
  },
});